- name: verify if rsync is installed
  stat: path=/usr/bin/rsync
  register: rsync_installed

- name: install rsync
  include_tasks: install-rsync.{{distro}}.yml
  when: not rsync_installed.stat.exists

- name: dump current db state
  raw: "{{docker_containers_volume_path}}/app/extra/db-backup.sh {{app_db_max_backups}}"
  args:
    warn: false
  register: raw_output

- debug: var=raw_output.stdout_lines

- name: download backup directories
  synchronize: src={{item}} dest="/tmp/{{domain}}/" \
               delete=yes recursive=yes copy_links=yes mode=pull
  with_items:
    - /backups

- debug:
    msg: "Dump was saved to /tmp/{{domain}}/backups*"
