USER_PROFILES    = [ "USER", "MOD", "ADMIN" ]
USER_STATES      = [ "ACTIVE", "SILENCED", "SUSPENDED" ]
EXCHANGES        = [ "BINANCE", "BITSO" ]
CURRENCIES       = [ "USD", "MXN" ]
CRYPTOCURRENCIES = [ "BTC", "ETH" ]
PRICE_DIRECTIONS = [ "ABOVE", "BELOW" ]
ALERT_METHODS    = [ "EMAIL" ]
# ALERT_METHODS    = [ "EMAIL", "PHONE", "SMS" ] TODO 28-11-2020 19:21
RESEND_TIMES     = [ "5 MINS", "10 MINS", "15 MINS", "30 MINS",
    "1 HOUR", "2 HOURS", "3 HOURS", "6 HOURS", "12 HOURS", "24 HOURS" ]
